// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFI8QGnZHre4JAwhH9dwDF2KtBWsRxUCI',
    appId: '1:914092108145:web:002f4c9f7c5ecd5d6feed0',
    messagingSenderId: '914092108145',
    projectId: 'e-learning-app-c05fc',
    authDomain: 'e-learning-app-c05fc.firebaseapp.com',
    storageBucket: 'e-learning-app-c05fc.appspot.com',
    measurementId: 'G-QDZXC06VKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9hSvRAbArwi-XfWV4HlRroZ_Twdrk2PY',
    appId: '1:914092108145:android:ee791dca7f2ddee26feed0',
    messagingSenderId: '914092108145',
    projectId: 'e-learning-app-c05fc',
    storageBucket: 'e-learning-app-c05fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAITFiy2mu79ZcLkpEd4BBx8X_rHnopYA8',
    appId: '1:914092108145:ios:73f88a5de414d4ed6feed0',
    messagingSenderId: '914092108145',
    projectId: 'e-learning-app-c05fc',
    storageBucket: 'e-learning-app-c05fc.appspot.com',
    androidClientId: '914092108145-bjagceqs1eaivg0mkcd6o9ga27k1d2pc.apps.googleusercontent.com',
    iosClientId: '914092108145-5v5mt90poj34tlk0a4pbs5lunjok4llf.apps.googleusercontent.com',
    iosBundleId: 'com.example.swproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAITFiy2mu79ZcLkpEd4BBx8X_rHnopYA8',
    appId: '1:914092108145:ios:73f88a5de414d4ed6feed0',
    messagingSenderId: '914092108145',
    projectId: 'e-learning-app-c05fc',
    storageBucket: 'e-learning-app-c05fc.appspot.com',
    androidClientId: '914092108145-bjagceqs1eaivg0mkcd6o9ga27k1d2pc.apps.googleusercontent.com',
    iosClientId: '914092108145-5v5mt90poj34tlk0a4pbs5lunjok4llf.apps.googleusercontent.com',
    iosBundleId: 'com.example.swproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFI8QGnZHre4JAwhH9dwDF2KtBWsRxUCI',
    appId: '1:914092108145:web:843975f056de388d6feed0',
    messagingSenderId: '914092108145',
    projectId: 'e-learning-app-c05fc',
    authDomain: 'e-learning-app-c05fc.firebaseapp.com',
    storageBucket: 'e-learning-app-c05fc.appspot.com',
    measurementId: 'G-37BKDLL518',
  );

}