// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE65m2tnyG5h1i1knvfAKBTvhAPePL26I',
    appId: '1:48669052280:web:0b66ae6524ee51d3a44c8d',
    messagingSenderId: '48669052280',
    projectId: 'project1-ce6a5',
    authDomain: 'project1-ce6a5.firebaseapp.com',
    storageBucket: 'project1-ce6a5.appspot.com',
    measurementId: 'G-K2NEBMR3SD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCooiUhOhEHtYpir6QjsgtgNvdagxIVM9w',
    appId: '1:48669052280:android:f74edea70b810253a44c8d',
    messagingSenderId: '48669052280',
    projectId: 'project1-ce6a5',
    storageBucket: 'project1-ce6a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeV-hrV34whi2IDjrED8TT2oQ2a2lHy4M',
    appId: '1:48669052280:ios:16fa759faf61b6a3a44c8d',
    messagingSenderId: '48669052280',
    projectId: 'project1-ce6a5',
    storageBucket: 'project1-ce6a5.appspot.com',
    iosBundleId: 'com.example.swproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeV-hrV34whi2IDjrED8TT2oQ2a2lHy4M',
    appId: '1:48669052280:ios:a78288f63e5d385ea44c8d',
    messagingSenderId: '48669052280',
    projectId: 'project1-ce6a5',
    storageBucket: 'project1-ce6a5.appspot.com',
    iosBundleId: 'com.example.swproject.RunnerTests',
  );
}
